### ISSUE TITLE
Drawer: move scrolling from "drawer" to "draw-holder"

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2498]
### Subject of the issue/enhancement/features
Currently, when the drawer contains a long list of items that extends beyond the viewport, the drawer-toolbar scrolls with the items. Result: Close button (and Back button) scroll out of sight.

I'd like to see the drawer-toolbar better imitate the behavior of a navbar and remain fixed in position. Currently the entire drawer scrolls by default. Can this behavior be moved/restricted to drawer-holder since that is the div that receives the various drawer extensions e.g., resources, search, glossary.

### My environment
* framework v4.2

### Steps to reproduce
1 Add a lot of items to Resources
2 Scroll
3 Observe drawer-toolbar

### Expected behaviour
I'd like to see the drawer-toolbar remain fixed while the Resource items scroll behind it.

### Actual behaviour
When scrolling a long list of Resources or Glossary items, the entire drawer scrolls.

**Comment by Link2Twenty** [comment]
I would probably go down the route of moving the scrolling to the drawer inner, like so:

I changed the width from 100% as that was going over and meaning `overflow-x: hidden` was required. I guess this change is technically not related.
```css
.drawer .drawer-toolbar {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  border-bottom: 1px solid @drawer-border-color;
}
```

Add a margin at the top for the toolbar then set the height to be 100% minus the margin and allow scrolling.
```css
.drawer .drawer-inner {
  border-left: 5px solid @drawer-border-color;
  overflow-y: auto;
  margin-top: ((@navigation-padding * 2) + @icon-size + 1);
  height: calc(100% - ((@navigation-padding * 2) + @icon-size + 1));
}
```

`.drawer .drawer-holder` would no longer need `padding-top`

![side-panel](https://user-images.githubusercontent.com/3534427/62781256-7a92e080-baaf-11e9-834c-0a1d0fc68396.gif)

**Comment by chucklorenz** [comment]
@Link2Twenty really appreciate you taking a look at this. Happy to have others help improve my code. But conceptually...if drawer-holder is the div that receives drawer extensions, is it not a more appropriate place for the scrolling to take place?

**Comment by Link2Twenty** [comment]
When I tried the styles here in my course the sidebar stopped having 100% height (as the drawer no longer had `height:100%;`), which prompted me to look for another solution. That being said I think you're right, from a logic viewpoint it makes much more sense to scroll within the handler so I've had a think.

Changing only `drawer-holder` I think we can keep the 100% height and have the toolbar remain static.
```css
.drawer .drawer-holder {
  position: absolute;
  top: ((@navigation-padding * 2) + @icon-size + 1);
  left: 0;
  right: 0;  
  bottom: 0;
  overflow-y: auto;
}
```

There is a chance the changes work perfectly and I'm doing something wrong when I'm testing them.

🙂
