### ISSUE TITLE
PageLevelProgress: *-title-inner overrides default when not in use

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2523]
pageLevelProgressIndicator.less overrides Adapt default display style even when `"_isCompletionIndicatorEnabled": false`
``` css
.menu-title-inner,
.menu-item-title-inner,
.page-title-inner,
.article-title-inner,
.block-title-inner,
.component-title-inner {
    display: inline-block;
}
```

I'm running:
* Framework v4.3.0
* PLP v4.1.2
* Chrome 77.0.3865.90
* Windows 10

### Steps to reproduce
1. Add a component
2. Configure as `"_isCompletionIndicatorEnabled": false`
3. Inspect display style of component-title-inner

### Expected behaviour

- Expecting that the default style `display: block` is retained when `"_isCompletionIndicatorEnabled": false`
- Expecting that the extension style `display: inline-block` is used only when needed, when `"_isCompletionIndicatorEnabled": true`

### Actual behaviour
The style `display: inline-block` is applied to all simply by installing the extension.

What impact does this have? On occasion some visual elements need to occupy the same space (e.g., component-title-inner) as the progressbar wants to. Doesn't seem to make sense to have PLP styles interfering when it is not being enabled. Also makes it more difficult to upgrade older courses. 

Would prefer a strategy that applies the inline-block style only when the Completion Indicator is enabled.
